### ISSUE TITLE
Not submitting

### ISSUE THREAD

**Issue by RoyWemmers** [geminilabs/site-reviews-v2#4]
Hi,

I'm using your plugin for this website i'm developing and really like it because of it's flexibility! But during testing i found out my form was not submitting, while when i first installed the plugin(about 45 mins ago) it did.
I reorderd the submit form fields via the index.php file. I disabled this as well and it also didn't resolve the issue.
I'm using version 2.15.11 and wordpress version 4.9.7

Kind Regards
Roy

**Comment by pryley** [comment]
Hi @RoyWemmers 

Please use the [support forum](https://wordpress.org/support/plugin/site-reviews/) for help with the plugin.

Github issues are only for problems with the source-code, your issue is likely due to a conflict with your theme or another plugin. I recommend the following troubleshooting steps:

**1. Temporarily switch to an official WordPress Theme.**

Try switching to an official WordPress Theme (i.e. Twenty Seventeen) and then see if you are still experiencing problems with the plugin. If this fixes the problem you were having then there is a compatibility issue with your theme.

**2. Temporarily deactivate all of your plugins.**

If switching to an official WordPress theme did not fix anything, the last thing to do is deactivate all of your plugins except for Site Reviews. If this fixes the problem you were having then there is a compatibility issue with one of your plugins.

The next thing to do is reactivate your plugins one-by-one until you find the plugin that is causing the problem. If you think that you’ve found the culprit, deactivate it and continue to test the rest of your plugins. Hopefully you won’t find any more, but it’s always better to make sure.

Once you know the plugin(s) responsible for the conflict, please let me know on the support forum or open an issue here specifically for that plugin conflict.
